fix unmarshal error when the tag contains omitempty
iamolegga/enviper pull request #15
Opened 2023-09-12 13:52 UTC by garenchan

## Issue

When the tag contains "omitempty", unmarshaling will result in the corresponding field being empty forever.

···bash
$ MYAPP_NAME=test go run main.go                                               
&{Name:}
···

···go
package main

import (
	"fmt"
	"strings"

	"github.com/iamolegga/enviper"
	"github.com/spf13/viper"
)

type Config struct {
	Name string `mapstructure:"name,omitempty"`
}

func main() {
	e := enviper.New(viper.New())
	e.SetEnvPrefix("MYAPP")
	e.AddConfigPath("/etc/myapp")
	e.SetConfigName("app")

	config := &Config{}
	if err := e.Unmarshal(config); err != nil {
		panic(err)
	}

	fmt.Printf("%+v\n", config)
}

···

2023-09-12 16:02 UTC, iamolegga requested changes

2023-09-12 16:02 UTC, iamolegga commented on enviper_test.go
> +	Foo    string `mapstructure:"foo,omitempty"`
let's add another field to check if the current one without tags is still correct

2023-09-13 01:11 UTC, garenchan commented on enviper_test.go
> +	Foo    string `mapstructure:"foo,omitempty"`
OK.

2023-09-13 02:16 UTC, garenchan commented on enviper_test.go
> +	Foo    string `mapstructure:"foo,omitempty"`
```
$ go test -v -run ./...
=== RUN   TestUnmarshal
=== RUN   TestUnmarshal/TestConfigWithEnvs
=== RUN   TestUnmarshal/TestOnlyConfig
=== RUN   TestUnmarshal/TestOnlyEnvs
=== RUN   TestUnmarshal/TestOnlyEnvsByCustomTag
=== RUN   TestUnmarshal/TestOnlyEnvsWithTagValue
=== RUN   TestUnmarshal/TestThrowsErrorWhenBrokenConfig
--- PASS: TestUnmarshal (0.02s)
    --- PASS: TestUnmarshal/TestConfigWithEnvs (0.01s)
    --- PASS: TestUnmarshal/TestOnlyConfig (0.00s)
    --- PASS: TestUnmarshal/TestOnlyEnvs (0.00s)
    --- PASS: TestUnmarshal/TestOnlyEnvsByCustomTag (0.00s)
    --- PASS: TestUnmarshal/TestOnlyEnvsWithTagValue (0.00s)
    --- PASS: TestUnmarshal/TestThrowsErrorWhenBrokenConfig (0.00s)
=== RUN   TestNew
--- PASS: TestNew (0.00s)
PASS
ok      github.com/iamolegga/enviper    0.104s
```

2023-09-13 12:33 UTC, merged